from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
import os
import httpx
from typing import Optional
from datetime import datetime

router = APIRouter()

TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID')

class EmergencyAlert(BaseModel):
    alert_type: str  # 'emergency', 'health_concern'
    message: str
    health_data: Optional[dict] = None
    user_name: Optional[str] = "Senior User"
    language: Optional[str] = "en"

class TelegramResponse(BaseModel):
    success: bool
    message: str

def format_telegram_message(alert: EmergencyAlert) -> str:
    """Format the emergency alert for Telegram"""
    
    # Emoji and headers based on alert type
    if alert.alert_type == 'emergency':
        header = "🚨 EMERGENCY ALERT 🚨"
        urgency = "⚠️ IMMEDIATE ATTENTION REQUIRED"
    else:
        header = "🏥 HEALTH CONCERN ALERT"
        urgency = "⚠️ Please check on the user"
    
    # Build message
    message_parts = [
        header,
        "",
        f"📅 Date & Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"👤 User: {alert.user_name}",
        "",
        urgency,
        "",
        f"📝 Message: {alert.message}",
        ""
    ]
    
    # Add health data if available
    if alert.health_data:
        message_parts.append("🏥 HEALTH DETAILS:")
        
        if 'sleep' in alert.health_data:
            message_parts.append(f"  😴 Sleep: {alert.health_data['sleep']} hours")
        
        if 'health_rating' in alert.health_data:
            rating = alert.health_data['health_rating']
            emoji = "😊" if rating >= 7 else "😐" if rating >= 5 else "😟"
            message_parts.append(f"  {emoji} Health Rating: {rating}/10")
        
        if 'pain' in alert.health_data:
            pain = alert.health_data['pain']
            if pain and pain.lower() != 'no' and pain.lower() != 'none':
                message_parts.append(f"  🤕 Pain: {pain}")
        
        if 'medications' in alert.health_data:
            med_status = alert.health_data['medications']
            emoji = "✅" if med_status.lower() in ['yes', 'taken', 'all'] else "❌"
            message_parts.append(f"  {emoji} Medications: {med_status}")
        
        if 'meals' in alert.health_data:
            meal_status = alert.health_data['meals']
            emoji = "✅" if meal_status.lower() in ['yes', 'eaten', 'regular'] else "❌"
            message_parts.append(f"  {emoji} Meals: {meal_status}")
        
        message_parts.append("")
    
    # Add action recommendation
    message_parts.extend([
        "📱 RECOMMENDED ACTIONS:",
        "1. Contact the user immediately",
        "2. Verify their current status",
        "3. Call emergency services if needed",
        "",
        "💬 This alert was automatically generated by SeniorSync"
    ])
    
    return "\n".join(message_parts)

@router.post("/alert", response_model=TelegramResponse)
async def send_emergency_alert(alert: EmergencyAlert):
    """
    Send an emergency alert to the configured Telegram chat
    """
    if not TELEGRAM_BOT_TOKEN:
        return TelegramResponse(
            success=False,
            message="TELEGRAM_BOT_TOKEN not configured in .env file"
        )
    
    if not TELEGRAM_CHAT_ID:
        return TelegramResponse(
            success=False,
            message="TELEGRAM_CHAT_ID not configured in .env file"
        )
    
    try:
        # Format the message
        formatted_message = format_telegram_message(alert)
        
        # Build Telegram API URL
        telegram_api_url = f'https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage'
        
        # Send to Telegram
        params = {
            'chat_id': TELEGRAM_CHAT_ID,
            'text': formatted_message,
            'parse_mode': 'HTML'
        }
        
        async with httpx.AsyncClient() as client:
            response = await client.post(telegram_api_url, json=params, timeout=10.0)
            response.raise_for_status()
            data = response.json()
            
            print(f"Telegram API Response: {data}")  # Debug logging
            
            if not data.get('ok'):
                error_msg = f"Telegram API error: {data.get('description', 'Unknown error')}"
                print(f"ERROR: {error_msg}")  # Debug logging
                return TelegramResponse(
                    success=False,
                    message=error_msg
                )
            
            return TelegramResponse(
                success=True,
                message="Emergency alert sent successfully to Telegram"
            )
    
    except httpx.HTTPError as e:
        return TelegramResponse(
            success=False,
            message=f"Failed to send Telegram message: {str(e)}"
        )
    except Exception as e:
        return TelegramResponse(
            success=False,
            message=f"An error occurred: {str(e)}"
        )

@router.get("/test")
async def test_telegram_connection():
    """
    Test the Telegram bot configuration
    """
    if not TELEGRAM_BOT_TOKEN:
        return {"success": False, "message": "TELEGRAM_BOT_TOKEN not configured"}
    
    if not TELEGRAM_CHAT_ID:
        return {"success": False, "message": "TELEGRAM_CHAT_ID not configured"}
    
    try:
        test_message = (
            "✅ TEST MESSAGE ✅\n\n"
            "This is a test message from SeniorSync.\n"
            "Your Telegram bot is configured correctly!\n\n"
            f"📅 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
            "You will receive emergency alerts at this chat."
        )
        
        # Build Telegram API URL
        telegram_api_url = f'https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage'
        
        params = {
            'chat_id': TELEGRAM_CHAT_ID,
            'text': test_message
        }
        
        async with httpx.AsyncClient() as client:
            response = await client.post(telegram_api_url, json=params, timeout=10.0)
            response.raise_for_status()
            data = response.json()
            
            if data.get('ok'):
                return {
                    "success": True, 
                    "message": "Test message sent successfully! Check your Telegram."
                }
            else:
                return {
                    "success": False,
                    "message": f"Telegram API error: {data.get('description', 'Unknown error')}"
                }
    
    except Exception as e:
        return {"success": False, "message": f"Error: {str(e)}"}
