import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    width: "100%",
    marginBottom: 20,
  },
  profileButton: {
    padding: 4,
  },
  greeting: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#003366",
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 18,
    color: "#333",
  },
  weatherCard: {
    width: "100%",
    backgroundColor: "#F0F7FF",
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#E3F2FD",
  },
  weatherMain: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  weatherTemp: {
    fontSize: 48,
    fontWeight: "bold",
    color: "#0A3D62",
    marginRight: 16,
  },
  weatherInfo: {
    flex: 1,
  },
  weatherCity: {
    fontSize: 20,
    fontWeight: "600",
    color: "#003366",
  },
  weatherDesc: {
    fontSize: 16,
    color: "#555",
    textTransform: "capitalize",
  },
  weatherDetails: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  weatherDetail: {
    fontSize: 14,
    color: "#666",
  },
  weatherError: {
    fontSize: 16,
    color: "#999",
    textAlign: "center",
  },
  button: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#66B2FF",
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderRadius: 12,
    marginBottom: 15,
    width: "100%",
  },
  emergencyButton: {
    backgroundColor: "#FF5252",
  },
  voiceEmergencyButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FF9800",
    paddingVertical: 20,
    paddingHorizontal: 20,
    borderRadius: 16,
    marginTop: 10,
    marginBottom: 15,
    width: "100%",
    borderWidth: 3,
    borderColor: "#F57C00",
  },
  voiceEmergencyRecording: {
    backgroundColor: "#F44336",
    borderColor: "#D32F2F",
  },
  voiceEmergencyText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
    marginLeft: 12,
  },
  icon: {
    marginRight: 10,
  },
  buttonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 24,
    width: "85%",
    maxWidth: 400,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: "#0A3D62",
    textAlign: "center",
    marginBottom: 20,
  },
  languageButton: {
    backgroundColor: "#F0F7FF",
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 2,
    borderColor: "#E3F2FD",
  },
  selectedLanguage: {
    backgroundColor: "#E3F2FD",
    borderColor: "#66B2FF",
  },
  languageButtonText: {
    fontSize: 18,
    fontWeight: "600",
    color: "#0A3D62",
    textAlign: "center",
  },
  cancelButton: {
    backgroundColor: "#fff",
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 12,
    marginTop: 8,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  cancelButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#666",
    textAlign: "center",
  },
});
